'caps : Hyper':
    y:
    u:
    i:
    o:
    p: 'soc.p' # Alfred clipboard
    '[': # Command Palette
        anybox: 'c.k'
        ide: 'sc.p'
        obsidian: 'c.p'
        warp: 'c.p'
        default: 'alfred: search, com.tedwise.menubarsearch'
    ']': '' # tell me this key is open
    h: # Previous Page
        discord: 'c.k rtn'
        raycast: 'esc'
        spotify: 'oc.lt'
        terminal: '"cdp" ++ rtn'
        default: 'c.['
    j:
    k:
    l:
    ';':
    qt:
    rtn: caps
    n:
        ide: 'oc.n'
        default: 'sc.n'
    m:
    ',':
    prd:
    '/':
    rtS:
    sb:

'tab : Tab':
    y:
    u:
    i: # First tab
        default: 'c.1'
    o: # Last Tab
        chrome: 'c.9'
        default: 't.0'
    p: # Pin Tab
        ide: 'c.k rtn'
        obsidian: 'toc.p'
        vivaldi: 'toc.p'
    '[': # Close all tabs to the left
        chrome: 't x h'
        ide: 'toc.e toc.['
    ']': # Close all tabs to the right
        chrome: 't x l'
        ide: 'toc.e toc.]'
    h: # Move tab left
        chrome: 'esc t h'
        ide: 'soc.lt'
        vivaldi: 'oc.lt'
    j: 'hs: Tab.previous'
    k: 'hs: Tab.next'
    l: # Move tab right
        chrome: 'esc t l'
        ide: 'soc.rt'
        vivaldi: 'oc.rt'
    ';':
    qt:
    rtn: # Restore tab
        default: 'sc.t'
    b:
    n: # New tab
        finder: 'c.n'
        ide: 'c.n s.o'
        default: 'c.t'
    m: 'hs: Tab.closeCurrent'
    ',': 'hs: Tab.closePrevious'
    prd: 'hs: Tab.closeNext'
    '/': # Close all other tabs
        chrome: 't x ;'
        ide: 'toc.e toc./'
    rtS: # Close all tabs
        ide: 'toc.e toc.qt'
    sb: # Pin tab
        ide: 'c.k rtn'
        obsidian: 'toc.p'
        vivaldi: 'toc.p'

'q : Pane':
    - all-right

'w':

'e':

'r : Calculator':
    b: ','
    y: '*'
    u: '1'
    i: '2'
    o: '3'
    p: '%'
    '[': 'dlt'
    ']': 'cln'
    h: '+'
    j: '4'
    k: '5'
    l: '6'
    ';': '0'
    qt: '='
    rtn: 'rtn'
    n: '-'
    m: '7'
    ',': '8'
    prd: '9'
    '/': '/'
    rtS: 'tab'
    sb: 'prd'

't : Test':
    - all-right

'y : Yank':
    - all-left

'u : AppShortcut':
    - all

'i : Make':
    - all-left

'o : Open':
    - all

'p : Paste':
    - all-left

'[ : Secondary':
    - all-left

'] : Tertiary':
    tab: null
    q: null
    w: null
    e: null
    r: 'raycast://extensions/raycast/system/restart'
    t: null
    caps: null
    a: null
    s: 'raycast://extensions/raycast/system/shut-down'
    d: null
    f: null
    g: null
    ltS: null
    z: null
    x: # VSCode Extensions
        ide: 'sc.x'
    c: null
    v: null
    b: null
    sb: null

'a : ChangeCase':
    - all-right

's : DefaultSnippets':
    d: '"dd();" ++ lt lt'
    e: '"elseif"'
    t: '"$this->"'
    y: '" && "'
    u:
    i: '"if () {}" ++ lt'
    o: '" + "'
    p: '" || "'
    '[': '"echo"'
    ']':
    h:
    j:
    k:
    l: '"console.log()" ++ lt'
    ';': '" : "'
    qt: '='
    rtn: '"return"'
    n:
    m:
    ',': '", "'
    prd:
    '/': '" ? "'
    rtS:
    sb:

'd : Vi':
    y: # 'moveToTopOfPage'
        default: 'hs: Vi.moveToTopOfPage'
    u: # 'pageUp'
        ide: 't.u'
        default: 'page_up'
    i: # 'moveToFirstCharacterOfLine'
        default: 'c.lt'
    o: # 'moveToEndOfLine'
        default: 'c.rt'
    p: null
    '[': # 'moveAndInsertAtFirstCharacterOfLine'
        ide: 'esc s.i'
        default: 'c.lt'
    ']': # 'moveAndAppendAtEndOfLine'
        ide: 'esc s.a'
        default: 'c.rt'
    h: 'lt'
    j: 'dn'
    k: 'up'
    l: 'rt'
    ';': # 'moveToPreviousWholeWord'
        default: 'esc s.b'
    qt: # 'moveToEndOfWholeWord'
        default: 'esc s.e'
    rtn: # 'moveToNextWholeWord'
        default: 'esc s.w'
    n: # 'moveToBottomOfPage'
        default: 'hs: Vi.moveToBottomOfPage'
    m: # 'pageDown'
        ide: 't.d'
        default: 'page_down'
    ',': # 'previousWord'
        default: 'o.lt'
    prd: # 'nextWord'
        default: 'o.rt'
    '/': # 'moveToPreviousSubword'
        default: 's.q'
    rtS: # 'moveToNextSubword'
        default: 'q'
    sb: # 'joinLines'
        ide: 'esc s.j x'

'f : General':
    y: '&'
    u: '_'
    i: '-'
    o: '" - "'
    p: '|'
    '[': '{'
    ']': '}'
    h: '#'
    j: '@'
    k: '$'
    l: '"- "'
    ';': '('
    qt: ')'
    rtn:
    n: '!'
    m: 'hs: CodeSnippets.null'
    ',': '`'
    prd: '"->"'
    '/': '~'
    rtS: '^'
    sb:

'g : Git':
    y:
        terminal: '"gbc" ++ rtn'
    u:
        browser: 'oc.u'
        terminal: '"nah"'
    i:
        terminal: '"git.checkout.include-all" ++ rtn'
    o:
        terminal: '"git.checkout" ++ rtn'
    p:
        ide: 'toc.g toc.p'
        terminal: '"gd" ++ rtn'
    '[':
        ide: 'toc.g oc.['
        terminal: '"gmm" ++ rtn'
    ']':
        terminal: '"grm" ++ rtn'
    h:
        terminal: '"git.status.with-summary" ++ rtn'
    j:
        ide: 'toc.g oc.j'
        terminal: '"grs" ++ rtn'
    k:
        ide: 'toc.g oc.k'
        terminal: '"git.commit ''''" ++ lt'
    l:
        ide: 'soc.g soc.h'
        terminal: '"git.log" ++ rtn'
        vivaldi: 'sc.l'
    ';':
        terminal: '"gum" ++ rtn'
    qt:
        terminal: '"goml" ++ rtn'
    rtn:
        ide: 'toc.g oc.]'
        terminal: '"gaa" ++ rtn'
    n:
        ide: '"```suggestion" ++ rtn rtn ++ "```" ++ up'
        terminal: '"git.branch.new ''''" ++ lt'
    m:
        ide: 'toc.g toc.m'
        terminal: '"git.branch.delete" ++ rtn'
    ',':
        browser: 'oc.i'
        terminal: '"git pull" ++ rtn'
    prd:
        ide: 'toc.g toc.j'
        terminal: '"git push" ++ rtn'
    '/':
        terminal: '"git stash -u -m ''''" ++ lt'
    rtS:
        terminal: '"gstp" ++ rtn'
    sb:
        ide: 'soc.g soc.sb'

'; : Command':
    tab: # Shift Tab
        default: 's.tab'
    q: null
    w:
    e:
    r: # Reload
        ide: 'soc.r'
        terminal: 'up rtn' # Run last command
        tinkerwell: 't.l c.r'
        default: 'c.r'
    t:
    caps: 'raycast://extensions/tegola/duck-duck-go-search/index'
    a: 'oc.\' # Alfred: Action file
    s: # Save
        ide: 'c.s esc'
        terminal: 'cln x rtn' # Save from vim
        default: 'c.s'
    d:
    f:
    g:
    ltS: 'alfred: commands, com.fuelingtheweb.commands'
    z: null
    x: # Cancel or delete
        anybox: 'c.dlt'
        fastmail: '#'
        finder: 'c.dlt'
        ide: 'sc.dlt'
        obsidian: 'sc.dlt'
        terminal: 't.c'
        default: 'dlt'
    c:
    v:
    b: null
    sb: null

'qt : ExtendedCommand':
    tab:
    q:
    w:
    e:
    r:
    t:
    caps: # Open Obsidian
        default: 'app: obsidian'
    a:
    s: # Cleanshot
        default: 'sc.5'
    d:
    f: # Reveal in sidebar
        default: 'sc.\'
    g:
    ltS:
    z:
    x:
    c:
    v:
    b:
    sb:

'z : CaseDialog':
    - all-right

'x : Execute':
    - all-right

'c : Code':
    y: # Code info
        default: 'c.k c.i'
    u: # Add use statement
        default: 'to.i'
    i: # Focus breadcrumbs
        default: 'sc.prd'
    o: # Go to definition
        default: 'oc.dn'
    p: # Compare active file with
        default: 'toc.c toc.w'
    '[': # Fold
        default: 'oc.['
    ']': # Unfold
        default: 'oc.]'
    h: # Previous member
        default: 'soc.up'
    j: # Move line down
        default: 'tc.dn'
    k: # Move line up
        default: 'tc.up'
    l: # Next member
        default: 'soc.dn'
    ';': # Toggle semicolon
        cursor: 't.;'
        default: 'o.;'
    qt: # Trigger Copilot
        default: 'o.\'
    rtn: # Select all
        default: 'tc.g'
    n: # Select next word
        default: 'c.d'
    m: # Multiple cursors down
        default: 'sto.dn'
    ',': # Toggle comma
        cursor: 't.,'
        default: 'o.,'
    prd: # Double arrow
        default: '" => "'
    '/': # Go to matching pair
        default: 'soc.m'
    rtS: # Go to matching bracket
        default: 't.m'
    sb: # Toggle comment
        default: 'c./'

'v : ViVisual':
    y: # 'selectToTopOfPage'
        ide: 'esc s.v g g'
        finder: 'so.up'
        default: 'sc.up'
    u: # 'selectLineUp'
        ide: 's.v k'
        default: 's.up'
    i: # 'selectToFirstCharacterOfLine'
        default: 'hs: SelectUntil.beginningOfLine'
    o: # 'selectToEndOfLine'
        ide: 't.v s.4 lt'
        default: 'sc.rt'
    p: null
    '[': null
    ']': null
    h: # 'selectLeft'
        ide: 't.v lt'
        default: 's.lt'
    j: # 'selectDown'
        ide: 't.v t.dn'
        default: 's.dn'
    k: # 'selectUp'
        ide: 't.v t.up'
        default: 's.up'
    l: # 'selectRight'
        ide: 't.v rt'
        default: 's.rt'
    ';': # 'selectToPreviousWholeWord'
        ide: 't.v s.b'
    qt: # 'selectToEndOfWholeWord'
        ide: 't.v s.e'
    rtn: # 'selectToNextWholeWord'
        ide: 't.v l s.w h'
    n: # 'selectToBottomOfPage'
        ide: 'esc s.v s.g'
        finder: 'so.dn'
        default: 'sc.dn'
    m: # 'selectLineDown'
        ide: 's.v j'
        default: 's.dn'
    ',': # 'selectPreviousWord'
        # ide: 's.v b'
        default: 'so.lt'
    prd: # 'selectNextWord'
        # ide: 's.v e'
        default: 'so.rt'
    '/': null
    rtS: null
    sb: null

'b':

'n : Change':
    - all-left

'm : Destroy':
    - all-left

', : SelectInside':
    - all-left

'prd : SelectUntil':
    - all-left

'/ : JumpTo':
    - all-left

'sb : Window':
    tab:
    q:
    w:
    e:
    r:
    t:
    caps:
    a:
    s:
    d:
    f:
    g:
    ltS:
    z:
    x:
    c:
    v:
    b:
        anybox: tc.s
        finder: oc.s
        mail: tc.s
        slack: sc.d
        tableplus: c.0
        vivaldi: tc.s
        outlook: 'menu: Microsoft Outlook, Sidebar, View'
        default: c.\
    y:
    u:
    i:
    o:
    p:
    open_bracket:
    close_bracket:
    h:
    j:
    k:
    l:
    semicolon:
    qt:
    rtn:
    n:
    m:
    comma:
    prd:
    slash:
    rtS:
